### PR TITLE
Build with the progen make_armcc tool

### PR DESCRIPTION
**Pull request by theotherjimmy**
Also adds a sh build script.

Works as expected on Linux (Ubuntu 14.04).

### CODE REVIEW

**Comment by theotherjimmy** [comment]
Hold on gentlemen, I'm breaking up the commit into an easier to understand history.

**Comment by theotherjimmy** [comment]
And We have two commits now!

**Comment by c1728p9** [comment]
This is blocked on #116 right?

**Comment by theotherjimmy** [comment]
Nope.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
I gave this a try locally, but it fails to compile.  It looks like the wrong flags are being passed to armasm ('-pd' rather than '-d'):
```
'Invoking: MCU Assembler'
armasm  -I.  -I..\..\..\source\usb  -I..\..\..\source\daplink\cmsis-dap  -I..\..\..\source\daplink\drag-n-drop  -I..\..\..\source\daplink\usb2uart  -I..\..\..\s
ource\daplink\settings  -I..\..\..\source\daplink  -I..\..\..\source\daplink\interface  -I..\..\..\source\cmsis-core  -I..\..\..\source\hic_hal  -I..\..\..\sour
ce\rtos  -I..\..\..\source\hic_hal\freescale\k20dx  -I..\..\..\source\hic_hal\freescale\iap\devices\MK20D5  -I..\..\..\source\hic_hal\freescale\iap\driver  -I..
\..\..\source\hic_hal\freescale\iap\devices -c --pd "DAPLINK_VERSION SETA 241"  --pd "HID_ENDPOINT SETA 1 "  --pd "MSC_ENDPOINT SETA 1 "  --pd "CDC_ENDPOINT SET
A 1 "  --pd "DAPLINK_IF SETA 1 "  --pd "DAPLINK_BUILD_KEY SETA 0x9B939E8F"  --pd "INTERFACE_K20D5 SETA 1 "  --pd "CPU_MK20DX128VFM5 SETA 1 "  --pd "DAPLINK_HIC_
ID SETA 0x97969900"  --pd "BL_TARGET_FLASH SETA 1 "  --no_unaligned_access  --cpu cortex-m4 --thumb  ..\..\..\source\hic_hal\freescale\k20dx\armcc/startup_MK20D
5.s -o build/startup_MK20D5.o
Warning: A3912W: Option 'c' is deprecated.
"..\..\..\source\hic_hal\freescale\k20dx\armcc/startup_MK20D5.s", line 463 (column 13): Error: A1137E: Unexpected characters at end of line
  463 00000400             #if defined(DAPLINK_IF)
                           ^
"..\..\..\source\hic_hal\freescale\k20dx\armcc/startup_MK20D5.s", line 465 (column 13): Error: A1137E: Unexpected characters at end of line
  465 00000000             #else
                           ^
"..\..\..\source\hic_hal\freescale\k20dx\armcc/startup_MK20D5.s", line 467 (column 13): Error: A1137E: Unexpected characters at end of line
  467 00000000             #endif
                           ^
3 Errors, 1 Warning
make: *** [build/startup_MK20D5.o] Error 1
```

CC: @theotherjimmy, @0xc0170

**Comment by 0xc0170** [comment]
> This is blocked on #116 right?

@theotherjimmy  
make armcc was added to progen 0.9.x. This needs an update: https://github.com/mbedmicro/DAPLink/blob/master/requirements.txt#L1

And as @c1728p9 pinpointed, We overlooked this: https://github.com/project-generator/project_generator/blob/08fb19c8db8eaa85b4574843559fb90b5aaf0803/project_generator/templates/makefile_armcc.tmpl#L16, it shall not be ``--pd``, please send a patch, and test it on some assembly files :-)

**Comment by theotherjimmy** [comment]
https://github.com/project-generator/project_generator/pull/416

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
This is blocked on https://github.com/project-generator/project_generator/pull/418

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by OwenBrotherwood** [comment]
Any chance of a how to using the open source compile contra the use of Keil

https://github.com/mbedmicro/DAPLink/blob/master/docs/DEVELOPERS-GUIDE.md

**Comment by c1728p9** [comment]
Hi @OwenBrotherwood, unfortunately DAPLink isn't currently setup to compile without Keil/ARMCC.  The code is all open source, so it is possible to port to GCC and build there. The version of RTX used in this project doesn't support GCC though so that would need to be added first. If you can make your configuration small enough, then you might be able to build with the code limited version of Keil.

**Comment by flit** [comment]
Imo, we do need to get to a point where we can build with gcc sometime soon.

**Pull request merged**
