### PR TITLE
Add support for MSD command 'erase.act'

### PR DESCRIPTION
**Pull request by c1728p9**
Add a mass storage command to erase flash contents on the target.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
This adds the feature requested in #106.

**Comment by sg-** [comment]
When the target is erased does it stay in a halted state? Is this behavior defined?

**Comment by c1728p9** [comment]
It behaves the same as drag-and-drop programming; If in hard reset mode then the it will stay halted, else if auto reset then it will start running

**Pull request merged**
