### PR TITLE
Updated Kinetis flash driver

### PR DESCRIPTION
**Pull request by flit**
- Updated flash driver and device support files to KSDK 2.0 version.
- Updated HIC YAML files.
- Removed source/hic_hal/freescale/iap/{devices,driver}.
- Updated K20DX and KL26Z device support files and moved under HIC
  source dir, so there is only one copy.
- Moved system_*.{c,h} to device support folder under HIC source dir.

_Note:_ This PR is dependant on PR #151, or the K20DX128 bootloader will fail to build because it is larger than 0x7C00 bytes. (It's only about 60 bytes over.)

### CODE REVIEW

**Comment by flit** [comment]
Rebased.

**Comment by flit** [comment]
@c1728p9 Is there anything you want me to change for this PR?

**Comment by c1728p9** [comment]
Not so far. PR looks good but will have to go through testing first.

**Comment by flit** [comment]
Of course.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@flit could you rebase this PR? There are a couple of conflicts. After that, I'll test one last time and then merge. I merged #151 today.

**Comment by flit** [comment]
@c1728p9 Just rebased.

**Comment by c1728p9** [comment]
Thanks, I'll rerun testing

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
@c1728p9 Any details about what failed?

**Comment by c1728p9** [comment]
This doesn't look like a real failure, I'll rerun

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
