### PR TITLE
[WIZnet] Added WIZwiki platform ( WIZwiki-W7500, WIZwiki-W7500P, WIZwiki-W7500ECO )

### PR DESCRIPTION
**Pull request by kaizen8501**
Added WIZnet platform to DAP Link

### CODE REVIEW

**Comment by c1728p9** [comment]
Hi @kaizen8501, please rebase this commit

**Comment by kaizen8501** [comment]
Hi @c1728p9. It is first time to do rebase in my life. So I have some mistake and I'm sorry about that make you feel annoyed.
I have done rebase. Is it right?

**Comment by c1728p9** [comment]
Hi @kaizen8501, you merged master into your branch, which is similar to a rebase and will allow me to merge this PR, so that is good. No need to be sorry. There is a first for everyone :smile:. 

Before I can test this PR you'll need to add these new projects to the supported configuration list found [here](https://github.com/mbedmicro/DAPLink/blob/master/test/info.py#L73). If you want these boards to be included in the next DAPLink release, you'll need to add them to the release list found [here](https://github.com/mbedmicro/DAPLink/blob/master/test/info.py#L23)

Finally, before I can merge this PR you'll need to sign the contributors agreement:
https://developer.mbed.org/contributor_agreement/

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
