### PR TITLE
Prevent lockup when target DP won't powerup

### PR DESCRIPTION
**Pull request by c1728p9**
If for some reason a targets DP won't powerup, DAPLink will get stuck in a loop waiting for this to occur. Add a timeout to prevent this timeout and to allow DAPLink to boot normally.

This problem can be reproduced on the FRDM-KW24D if target firmware sets pin PTB19 low immediately after boot.

CC: @flit

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
Strange, I don't see a PTB19 pin on the KW24D pinout. Do you mean PTA19 (XTAL0)?

**Comment by c1728p9** [comment]
You'll need to look at the reference manual to find it. It is an internal only pin.

**Comment by flit** [comment]
Thanks, I see it now. Any idea why putting the modem into reset causes the DP to not power up?

**Comment by c1728p9** [comment]
I have no idea how a processor could turn off and keep off its own DP.  This problem is easy to reproduce if you or someone else wanted to investigate it further. Oddly enough, jtag seems to work normally.
CC: @maclobdell

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by flit** [comment]
Agreed, I don't see how that's possible. I'll ask around.

What kind of timing is required for pulling PTB19 low? Is there an amount of time after which it can be pulled low without causing this problem?

**Comment by c1728p9** [comment]
Pull it low at any time and it causes problems. It needs to be pulled low on boot to cause daplink to get stuck (which this PR fixes)

**Comment by flit** [comment]
I see. Does the DP return to normal if you set PTB19 high?

I asked the connectivity software team if they have ever seen debug issues caused by this pin (they use J-Links).

**Comment by c1728p9** [comment]
I'm not sure if setting PTB19 high fixes this, as the micro doesn't seem to work properly once it is low. I tried programming with an external j-link and it seemed to have this same problem with swd, but not with jtag. You might ask the connectivity specifically if they have seen this with swd.

**Comment by flit** [comment]
Ok, thanks.

**Comment by flit** [comment]
@c1728p9 Feedback from the connectivity software team:
- If the Radio_RST is asserted after the MCU initializes the clock reference to use the CLK from the radio, this would leave the MCU with no clock.
- We noticed that the internal clock from the KW2xD is not calibrated they could try using FEI but first calibrate the internal clock using radio's clock as external reference. https://community.nxp.com/docs/DOC-333573 
- RST_B is routed to PTB19 and the SWD pins are in PTAx so the RST asserting itself should not affect the SWD/JTAG interface.

**Pull request merged**
