### PR TITLE
Update serial test to make test cases modular

### PR DESCRIPTION
**Pull request by c1728p9**
Create a SerialTester class to wrap common serial port operations.
Use this class to remove extra copy-paste code.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by sg-** [comment]
LGTM 👍

**Comment by c1728p9** [comment]
Rebased cleanly onto master

**Pull request merged**
