### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Palmitoxico**
Just correct the README.md "firware" to "firmware".

### CODE REVIEW

**Comment by c1728p9** [comment]
Thanks for the typo fix

Please accept the contributors agreement:
https://developer.mbed.org/contributor_agreement/

**Comment by Palmitoxico** [comment]
Contributors Agreement accepted!

**Comment by c1728p9** [comment]
Thanks!

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
