### PR TITLE
Fix serial problems

### PR DESCRIPTION
**Pull request by c1728p9**
Fix problems that occur when serial data is sent by the target while DAPLink is booting.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by jupe** [comment]
this seems to related to all targets, is it?

**Comment by c1728p9** [comment]
Hi @jupe, yep, this problem is common to all interfaces. It was introduced in the 0243 release.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
