### PR TITLE
Add target GR-PEACH (rebase 2)

### PR DESCRIPTION
**Pull request by d-kato**
Original pull request is #163.

### CODE REVIEW

**Comment by c1728p9** [comment]
Thanks for the update @d-kato

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@d-kato , testing passed and the PR looks good. I can't merge though, until the contributor agreement is signed. It can be found here:
https://developer.mbed.org/contributor_agreement/

**Comment by d-kato** [comment]
Hi @c1728p9, I signed. Please merge this PR.

**Pull request merged**
