### PR TITLE
Update ncs36510 flash algo to fix erase

### PR DESCRIPTION
**Pull request by c1728p9**
Rebuild the ncs36510 flash algo with a fix to properly wait for mass erase to complete. This allows the flash algo to work correctly when flash init is not called before each flash operation.

### CODE REVIEW

**Comment by c1728p9** [comment]
CC: @maclobdell

**Comment by maclobdell** [comment]
cc @danclement, @jacobjohnson-ON

**Comment by c1728p9** [comment]
This is built from https://github.com/mbedmicro/FlashAlgo/pull/35

**Pull request merged**
