### PR TITLE
add support for ncs36510

### PR DESCRIPTION
**Pull request by maclobdell**
add support for ncs36510

also, update interface led code

### CODE REVIEW

**Comment by maclobdell** [comment]
@c1728p9 can you take a look at this.  any estimated time it could be merged or reworked?

**Comment by danclement** [comment]
This pull request has been open since June 2016, what do we need to do to get it completed so I can check this action item off and stop tracking it :)?

**Comment by maclobdell** [comment]
it is getting added to an upcoming sprint.  we will keep you updated.  sorry for the long delay in mainlining this.

**Comment by c1728p9** [comment]
This has been moved to #226

**Comment by maclobdell** [comment]
I think you mean it has been moved to https://github.com/mbedmicro/DAPLink/pull/243

**Comment by c1728p9** [comment]
Oops yeah, thanks for the correction.

**Pull request closed without merging**
