### PR TITLE
Add initial automation support for lpc11u35

### PR DESCRIPTION
**Pull request by c1728p9**
Allow start_bl.act to switch the lpc11u35 into ISP mode. Since there
is no way to exit ISP mode from the host PC, setup the watchdog to
trigger a reset which starts DAPLink after ~30 seconds.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by sg-** [comment]
LGTM 👍

**Pull request merged**
