### PR TITLE
Fix k20dx uart setting change

### PR DESCRIPTION
**Pull request by c1728p9**
Fix uart settings change problem on k20dx and add a test for this.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by sg-** [comment]
LGTM 👍

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
Updated to fix the KL26 and cover a few more cases.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
