### PR TITLE
Fix ".DS_Store" problem on macOS

### PR DESCRIPTION
**Pull request by cederom**
Verify if project path is a directory.
This fixes ".DS_Store" problem on macOS.

Signed-off-by: CeDeROM Tomasz CEDRO <tomek@cedro.info>

### CODE REVIEW

**Comment by cederom** [comment]
This seems to fix https://github.com/mbedmicro/DAPLink/issues/301 :-)

**Comment by cederom** [comment]
i have also added simple shell script to loop testing on a local machine.. do we also want it here? :-)

**Comment by c1728p9** [comment]
Probably best as its own PR. I wouldn't worry about moving it now

**Comment by cederom** [comment]
would like to put  more patches here.. do we prefer bundle or separate PR per issue? :-)

**Comment by c1728p9** [comment]
Any changes that can stand alone should go on a separate PR.

**Pull request merged**
