### PR TITLE
[IntelHex] Adding parsing of extended segment address record.

### PR DESCRIPTION
**Pull request by kgills**

### CODE REVIEW

**Comment by c1728p9** [comment]
Thanks for the PR. Were you seeing problems without the extended segment address record? If so, what tools were you using?

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by kgills** [comment]
I was using ARM_GCC to compile the application and objcopy to create the hex file.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@kgills what was the behavior without this fix? Were the wrong addresses flashed?

**Comment by kgills** [comment]
Yeah it wasn't parsing the record so it was flashing the code to zero.

`:020000021000EC
:100000000080022099210100D3210100D5210100A7`

The target that I'm working has a ROM at address 0 and the application code we're flashing needs to go to address 0x1000.

**Comment by kgills** [comment]
Any more thoughts on this one? I can give you the hex file if you want to test it out.

**Comment by c1728p9** [comment]
Yes, please do.

**Pull request merged**
