### PR TITLE
Master

### PR DESCRIPTION
**Pull request by elektor-labs**
Added Elektor CoCo-ri-Co platform.

### CODE REVIEW

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
Please accept the contributors agreement:
https://developer.mbed.org/contributor_agreement/

**Comment by c1728p9** [comment]
Please add the cocorico to FIRMWARE_NAME_TO_BOARD_ID, run testing and attach the results

**Comment by c1728p9** [comment]
Hi @elektor-labs, since #114 was merged, you'll need to add this as a configuration in SUPPORTED_CONFIGURATIONS rather than FIRMWARE_NAME_TO_BOARD_ID.

**Comment by c1728p9** [comment]
Hi @elektor-labs, please rebase this PR and add entries in PROJECT_RELEASE_INFO SUPPORTED_CONFIGURATIONS in info.py if you want to be included in the upcoming release. You'll also need to sign the contributor's agreement with an mbed account if you haven't already:
https://developer.mbed.org/contributor_agreement/

**Comment by elektor-labs** [comment]
Hi,

At the moment I do not have the time to dive into this again. Is it important to be included in the upcoming release? Is there a deadline? Isn’t it enough that my platform is already integrated in the main mbed repository?

Best regards,

Clemens Valens
Technical Manager

http://www.elektor-labs.com/

E clemens.valens@eimworld.com
T +31 (0)46 4389444      M +33 (0)666404766
F +31 (0)46 4370161     S clemens_valens
P.O. Box 11 – 6114 ZG Susteren – Netherlands

Elektor is part of EIM – Elektor International Media BV

Visit us at electronica:
November 08 – 11, 2016
Booth EOE 200, Entry East

De : Russ Butler [mailto:notifications@github.com]
Envoyé : vendredi 16 septembre 2016 05:51
À : mbedmicro/DAPLink
Cc : labs@elektor.com; Mention
Objet : Re: [mbedmicro/DAPLink] Master (#109)


Hi @elektor-labs<https://github.com/elektor-labs>, please rebase this PR and add entries in PROJECT_RELEASE_INFO SUPPORTED_CONFIGURATIONS in info.py if you want to be included in the upcoming release. You'll also need to sign the contributor's agreement with an mbed account if you haven't already:
https://developer.mbed.org/contributor_agreement/

**Comment by c1728p9** [comment]
Hi @elektor-labs, a requirement for getting a platform in the main mbed repository is to sign the contributors agreement. Which account did you use to sign it? That will be sufficient.

Unfortunately the cocorico platform didn't make it into the version 0242 release of DAPLink.

Updating the table entries to enable releases and testing is very easy, so if you want I could do it. Just let me know. I would also encourage you to run the DAPLink test suite to validate your board, but this is not a requirement to get this PR merged.

**Comment by elektor-labs** [comment]
As far as I know I already signed the contributor’s agreement (user “clemo”). This is from a message I received on April 28, 2016:

> You have now been added to the Community Contributor team, you should now have access to your platform page. https://developer.mbed.org/platforms/CoCo-ri-Co/

Or is this about another Community Contributor team? Anyway, I signed it again just now.

If you could add the platform for me, that would be great. You know, this is not my daily work and it would cost me quite some time to dive in again, etc. I thought that I did it right the first time, but apparently not. Your help would be greatly appreciated!

**Comment by c1728p9** [comment]
Hi @elektor-labs, the account clemo works. I'll update this PR as well.

**Comment by c1728p9** [comment]
Hi @elektor-labs, I updated this and moved it to #190.

**Pull request closed without merging**
