### PR TITLE
Build variants documentation.

### PR DESCRIPTION
**Pull request by flit**
Add documentation of the variants of DAPLink target build output.

### CODE REVIEW

**Comment by c1728p9** [comment]
Thanks for the doc updates! Could have one of the main pages link to this?

**Comment by c1728p9** [comment]
Table of contents is a good idea.  As for this, I would link to it somewhere from the developers guide.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
Thanks for the doc updates! There no link to the index, but this can be added later.

**Comment by flit** [comment]
@c1728p9 Which index do you mean?

**Comment by c1728p9** [comment]
I meant there is no link from the main page README.txt to the table of contents in docs/README.md.

**Comment by flit** [comment]
Oh, right. That would be useful…

**Pull request merged**
