### PR TITLE
README and DOC updates.

### PR DESCRIPTION
**Pull request by cederom**
Signed-off-by: CeDeROM Tomasz CEDRO <CeDeROM@tlen.pl>

### CODE REVIEW

**Comment by cederom** [comment]
tomorrow I will also commit DAPLinkDeveloperGuide so we can merge all changes at once :-)

**Comment by cederom** [comment]
I decided to produce one centralized document, `The DAPLink Handbook`, that will contain both `User Manual` and `Developer Manual`. This will keep things coherent and remove additional work to keep documents in sync because all will be in one place.. and we can make it a nice book :-)

**Comment by cederom** [comment]
I am adding changes in forced mode so the file will change with time.. its almost finished just some final chapters remaining.. will let you know when its ready.. probably start of next week.. now time to do some SkyDive! Have a great weekend! :-)

**Comment by cederom** [comment]
Okay so The DAPLink Handbook proposition is ready. As discussed with @AnotherButler @c1728p9 I will cut the sections into separate files and create ToC within doc/README.md tomorrow :-)

**Comment by cederom** [comment]
All is done now, ready for review :-)

**Comment by cederom** [comment]
Any feedback @AnotherButler @c1728p9 @sg- ? :-)

**Comment by sg-** [comment]
There is a lot to review here... but should have feedback in a few days

**Comment by cederom** [comment]
ACK! :-) I have some other ideas to put here, but will wait until review is finished, no rush! :-)

**Pull request closed without merging**
