### PR TITLE
Add files to support the board id 1021

### PR DESCRIPTION
**Pull request by ytsuboi**
and changed drive names.

### CODE REVIEW

**Comment by sg-** [comment]
LGTM 👍

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
@ytsuboi, looks like the tests failed because the firmware "lpc11u35_ssci_chibi_if" needs to be added to SUPPORTED_CONFIGURATIONS in info.py.

**Comment by c1728p9** [comment]
Hi @ytsuboi, release 0242 will go out soon. Please rebase this PR onto master and update  SUPPORTED_CONFIGURATIONS and PROJECT_RELEASE_INFO so I can test and merge this PR for the release.

**Comment by ytsuboi** [comment]
Hi @c1728p9, can I do that by early next week? I'm on business trip. When will you release 0242?

**Comment by c1728p9** [comment]
Hi @ytsuboi, the release is going out today. I can try updating this patch for you if you are out.

**Comment by ytsuboi** [comment]
@c1728p9 Please! Thanks!

**Comment by c1728p9** [comment]
@ytsuboi, does the chibi:bit have a platform page?

**Comment by ytsuboi** [comment]
@c1728p9 Yes, working on currently. It will be released in near future.

**Comment by c1728p9** [comment]
@ytsuboi, what is the target name? Is it in mbed?

**Comment by c1728p9** [comment]
Closing this PR since #158 bring this in.

**Pull request closed without merging**
