### PR TITLE
Documentation improvements and additions

### PR DESCRIPTION
**Pull request by sukidog**

### CODE REVIEW

**Comment by sukidog** [comment]
Change to target_cfg_t struct in PORT_TARGET.MD was unintentional (copy&paste goof), but it isn't harmful/wrong.

**Comment by sukidog** [comment]
Sorry. Messed up this PR a bit. Will create another one

**Comment by c1728p9** [comment]
If you force push to doc_enhancements you can update this PR (even overwriting old commits if you want), so you don't need to close it and open a new one.

**Comment by sukidog** [comment]
Already closed. I accidentally mixed two sets of changes into the PR. Was
cleaner/easier to redo. #80 and #82 are the only active PRs at this point.
All others (from me) are closed and should be ignored.

**Pull request closed without merging**
