### PR TITLE
[Test] Exctracting starting address from hex file

### PR DESCRIPTION
**Pull request by kgills**
We need the address offset when comparing the loaded data.

### CODE REVIEW

**Comment by c1728p9** [comment]
Thanks for the change. Is this needed to support a new target?

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by kgills** [comment]
The MAX32625NEXPAQ has it's own bootloader so we have to offset the application code.

**Comment by kgills** [comment]
Does the CI give any specific reason why it failed? I can't see any details.

**Comment by c1728p9** [comment]
Hi @kgills, unfortunately the test output is not publicly visible currently. Here is the part of the test that is failing:
```
18:06:21 Checking that assert file was created
18:06:21 Checking that assert file persists if->bl
18:06:21 Checking that assert file persists bl->if
18:06:21 Traceback (most recent call last):
18:06:21   File "test/run_test.py", line 699, in <module>
18:06:21     main()
18:06:21   File "test/run_test.py", line 677, in main
18:06:21     tester.run_tests()
18:06:21   File "test/run_test.py", line 236, in run_tests
18:06:21     daplink_test(test_configuration, test_info)
18:06:21   File "C:\Jenkins\workspace\DAPLink-test_hw\test\test_daplink.py", line 137, in daplink_test
18:06:21     test.set_expected_data(bin_data)
18:06:21 TypeError: set_expected_data() takes exactly 3 arguments (2 given)
```

**Comment by kgills** [comment]
Try testing it now, I updated that those function calls.

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Comment by c1728p9** [comment]
Thanks. I triggered testing again.

**Comment by c1728p9** [comment]
Similar error:
```
14:30:39 Traceback (most recent call last):
14:30:39   File "test/run_test.py", line 699, in <module>
14:30:39     main()
14:30:39   File "test/run_test.py", line 677, in main
14:30:39     tester.run_tests()
14:30:39   File "test/run_test.py", line 236, in run_tests
14:30:39     daplink_test(test_configuration, test_info)
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\test_daplink.py", line 138, in daplink_test
14:30:39     test.run()
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\test_daplink.py", line 90, in run
14:30:39     super(DLMassStorageTester, self).run()
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\msd_test.py", line 240, in run
14:30:39     if self._check_data_correct(self._expected_data, test_info, self._start):
```

**Comment by c1728p9** [comment]
Here is the whole log for the failing board:
```
14:29:55 Board: Name=FRDM-K64F Unique ID=0240000028884e45001070116bf000478021000097969900
14:29:55 Application: Name=k20dx_frdmk64f_if
14:29:55 Bootloader: Name=k20dx_bl
14:29:55 Target: Name=FRDM-K64F
14:29:55 SubTest: load_interface
14:29:55 SubTest: set_mode
14:29:55 changing mode IF -> BL
14:29:55 SubTest: wait_for_remount
14:29:55 unmount took 1.10100007057 s
14:29:55 mount took 5.54200005531 s
14:29:55 programming took 5.37199997902 s
14:29:55 SubTest: wait_for_remount
14:29:55 unmount took 0.700999975204 s
14:29:55 mount took 3.35800004005 s
14:29:55 SubTest: set_mode
14:29:55 Interface crc: 0x50884233
14:29:55 SubTest: load_bootloader
14:29:55 SubTest: set_mode
14:29:55 programming took 2.62799978256 s
14:29:55 SubTest: wait_for_remount
14:29:55 unmount took 1.61599993706 s
14:29:55 mount took 3.49099993706 s
14:29:55 SubTest: set_mode
14:29:55 Bootloader crc: 0x26259eee
14:30:39 SubTest: daplink_test
14:30:39 SubTest: Assert Test
14:30:39 Triggering assert by creating ASSERT.ACT
14:30:39 SubTest: wait_for_remount
14:30:39 unmount took 1.13199996948 s
14:30:39 mount took 3.50600004196 s
14:30:39 SubTest: test_fs
14:30:39 chkdsk returned 0
14:30:39 SubTest: test_fs_contents
14:30:39 File Q:\MBED.HTM valid
14:30:39 File Q:\DETAILS.TXT valid
14:30:39 File Q:\ASSERT.TXT valid
14:30:39 SubTest: test_details_txt
14:30:39 SubTest: parse_kvp_file
14:30:39 SubTest: test_details_txt
14:30:39 SubTest: parse_kvp_file
14:30:39 Checking that assert file was created
14:30:39 Checking that assert file persists if->bl
14:30:39 Checking that assert file persists bl->if
14:30:39 SubTest: Shutil binary file load interface
14:30:39 Loading took 4.50600004196s
14:30:39 Programming rate 21588.9922535B/s
14:30:39 SubTest: wait_for_remount
14:30:39 unmount took 1.10100007057 s
14:30:39 mount took 3.13800001144 s
14:30:39 SubTest: test_fs
14:30:39 chkdsk returned 0
14:30:39 SubTest: test_fs_contents
14:30:39 File Q:\MBED.HTM valid
14:30:39 File Q:\DETAILS.TXT valid
14:30:39 SubTest: test_details_txt
14:30:39 SubTest: parse_kvp_file
14:30:39 SubTest: test_details_txt
14:30:39 SubTest: parse_kvp_file
14:30:39 SubTest: test_fs
14:30:39 chkdsk returned 0
14:30:39 Traceback (most recent call last):
14:30:39   File "test/run_test.py", line 699, in <module>
14:30:39     main()
14:30:39   File "test/run_test.py", line 677, in main
14:30:39     tester.run_tests()
14:30:39   File "test/run_test.py", line 236, in run_tests
14:30:39     daplink_test(test_configuration, test_info)
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\test_daplink.py", line 138, in daplink_test
14:30:39     test.run()
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\test_daplink.py", line 90, in run
14:30:39     super(DLMassStorageTester, self).run()
14:30:39   File "C:\Jenkins\workspace\DAPLink-test_hw\test\msd_test.py", line 240, in run
14:30:39     if self._check_data_correct(self._expected_data, test_info, self._start):
```
If you aren't already, you might want to specify flags to run daplink specific tests ```--testdl``` and load a new bootloader ```--loadbl```. These aren't turned on by default.

**Comment by kgills** [comment]
Those flags exposed the problem for me. Please try the CI test again.

**Comment by c1728p9** [comment]
Good to hear. Retriggering now

**Comment by c1728p9** [comment]
@mbed-bot: TEST

**Pull request merged**
