### PR TITLE
Update to CMSIS-DAP source from CMSIS 5

### PR DESCRIPTION
**Pull request by flit**
This patch synchronizes the standard CMSIS-DAP sources in source/daplink/cmsis-dap with the version of CMSIS-DAP from CMSIS 5. New features are the DAP_ExecuteCommands command and SWO support. Note that SWO is not actually supported by any HICs yet.

### CODE REVIEW

**Comment by cederom** [comment]
@flit @c1728p9 I am working on SWD lock mechanism in DAPLink to prevent concurrent access. I would like to commit this change in order to put my changes on top.

At the moment I cannot see sensible way to implement lock mechanism without modification of this part of the code, which is used in HID access to Debug. DAPLink also uses SWD in UMS access to Flash firmware, and CDC+Reset handler in order to Reset target..

I would like to perform local changes to the DAPLink source tree to achieve my goal. Then propose upstream changes to CMSIS-DAP. Then merge those changes already containing lock mechanism back here when ready. Is that okay?

**Comment by flit** [comment]
@cederom Well, I guess I don't understand the benefit of modifying this PR to include the lock support, instead of separately merging this PR followed by a PR adding the lock support.

**Comment by cederom** [comment]
yea @flit ! that is exactly what i mean, tho have this pr first included! :-) :-)

**Comment by c1728p9** [comment]
Thanks for making this update @flit it looks good!

**Pull request merged**
